app: template
name: nextjs # (必选) 组件实例名称。
component: multi-scf

inputs:
  name: ${name}-serverless-${app} # 云函数名称，默认为 ${name}-${stage}-${app} ,也可以直接写死
  region: ${env:REGION} # 云函数所在区域
  namespace: gocyber-fe # 命名空间
  type: web # 函数类型
  timeout: 59
  isAutoPublish: true # 是否每次部署时，自动发布函数版本
  publishDescription: nextjs_serverless_template # 发布版本描述

  functions:
    user-detail:
      type: web
      image: # 镜像配置
        registryId: ${env:REGISTRY_ID} # 容器镜像服务名称，企业版必须
        imageType: ${env:IMAGE_TYPE} # 镜像类型：personal - 个人，enterprise - 企业版，public - 镜像模板
        imageUrl: ${env:IMAGE_URL_PREFIX}/gocyber-fe/dashboard:${env:DOCKER_IMAGE_TAG} # DOCKER_IMAGE_TAG是由githubAction传进来的

  triggers:
    - type: apigw   # api网关配置
      parameters:
        serviceName: ${env:API_GW_NAME}
        serviceId: ${env:API_GW_ID}
        protocols:
          - http
          - https
        netTypes:
          - OUTER
        environment: release
        endpoints:
          - path: /serverless/fe/template
            method: get

